## Install the `rest-client` VS Code extension to use this file
## https://github.com/Huachao/vscode-restclient

@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}
@proto = http


GET {{proto}}://{{host}}/api/reset

###
GET {{proto}}://{{host}}/api/clear

###
GET {{proto}}://{{host}}/api/status

###
GET {{proto}}://{{host}}/api/devices

###

GET {{proto}}://{{host}}/api/randint32

###

GET {{proto}}://{{host}}/api/randuniform

###

GET {{proto}}://{{host}}/api/randnormal

###

GET {{proto}}://{{host}}/api/randbase64

###

GET {{proto}}://{{host}}/api/devices

###

GET {{proto}}://{{host}}/api/json/randint32

###

GET {{proto}}://{{host}}/api/json/randuniform

###

GET {{proto}}://{{host}}/api/json/randnormal

###

GET {{proto}}://{{host}}/api/json/randbase64

###

GET {{proto}}://{{host}}/api/json/devices